### PR TITLE
Schedule addmore

### PR DESCRIPTION
**Pull request by hoatran1403**
added redux, react-redux, "add item" button

### CODE REVIEW

**Comment by ejuor** [comment]
Do the values placed inside the textbox update the entries in the table (on the client)? Or will it submit then fetch from the database first before updating the entries?

Also, there's an error in the devtools when I run it:

`Store does not have a valid reducer. Make sure the argument passed to combineReducers is an object whose values are reducers.`

**Comment by hoatran1403** [comment]
No data fetched yet @ejour. In this PR, I just want to setup redux basic folder structure for project. regarding to "add item", it's just a toogle button basically, nothing more. currently, I'm trying to add test data as a json file. It might look like this:
`{
    "teams": [
        {
            "name": "Meerkat Sundial",
            "members": [
                {
                    "name": "musecode",
                    "availTime": "5-10",
                    "timezone": "+12"
                },
                {
                    "name": "nionata",
                    "availTime": "5-10",
                    "timezone": "-5"
                }
            ]
        }
    ]
}`

**Comment by hoatran1403** [comment]
regarding to to devtool's console warning, it's because we didn't have any reducer yet

**Comment by hoatran1403** [comment]
Don't worry about that @ejuor, We are all just beginner and learning together. I'm a dummy beginner and make lots of mistakes so all your comments are valuable for me.

**Pull request merged**
